version: '3.3'

services:
  react:
    build: .
    command: sh -c 'yarn install && yarn start'
    build:
      context: ./
      target: base
    tty: true
    environment:
      NODE_OPTIONS: --openssl-legacy-provider
      GRAPHQL_CODEGEN_ENDPOINT: ${GRAPHQL_CODEGEN_ENDPOINT:-http://localhost:7000/graphql/}
      REACT_APP_GRAPHQL_ENDPOINT: ${REACT_APP_GRAPHQL_ENDPOINT:-http://localhost:7000/graphql/}
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - '3080:3080'
